name: pgde

version: 0.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection:
  intl:
  grpc: ^2.1.3
  protobuf: ^1.0.1
  email_validator: '^1.0.0'
  flutter_form_builder: ^3.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  args:
  intl_translation:
  test:

flutter:
  uses-material-design: true